apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: hello
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
        # env:
        #   - name: ALLOW_EMPTY_PASSWORD
        #     value: "yes"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: "/hello"
        #     port: 80
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        ports:
        - containerPort: 80
          name: hello
        # volumeMounts:
        # - name: localtime
        #   mountPath: "/etc/localtime"
      # volumes:
      # - name: localtime
      #   hostPath:
      #     path: "/usr/share/zoneinfo/Asia/Taipei"
      restartPolicy: Always
      # imagePullSecrets:
      # - name: docker-login
