name: Build and deploy an app to AKS
"on":
    push:
        branches:
            - main
    workflow_dispatch: null
env:
    AZURE_CONTAINER_REGISTRY: jkatariyatest
    CLUSTER_NAME: jkatariyatest
    CONTAINER_NAME: main
    DEPLOYMENT_MANIFEST_PATH: ./docker/azure-vote/azure-vote/manifests
    RESOURCE_GROUP: jkatariyatest
jobs:
    buildImage:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Azure login
              uses: azure/login@v1.4.6
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            - name: Build and push image to ACR
              run: |
                az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .
    deploy:
        permissions:
            actions: read
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        needs:
            - buildImage
        steps:
            - uses: actions/checkout@v3
            - name: Azure login
              uses: azure/login@v1.4.6
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            - name: Set up kubelogin for non-interactive login
              uses: azure/use-kubelogin@v1
              with:
                kubelogin-version: v0.0.25
            - name: Get K8s context
              uses: azure/aks-set-context@v3
              with:
                admin: "false"
                cluster-name: ${{ env.CLUSTER_NAME }}
                resource-group: ${{ env.RESOURCE_GROUP }}
                use-kubelogin: "true"
            - name: Deploys application
              uses: Azure/k8s-deploy@v4
              with:
                action: deploy
                images: |
                    ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
                manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
